[".config/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "8h"

[".config/nvim/"]
    type = "archive"
    url = "https://github.com/nvim-treesitter/nvim-treesitter/archive/master.tar.gz"
    stripComponents = 1
    refreshPeriod = "168h"
		include = ["*/queries/**"]
