"$schema" = "https://starship.rs/config-schema.json"
palette = "catppuccin_frappe"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
$env_var\
$character"""

right_format = """
$nix_shell\
$docker_context\
$cmd_duration"""

[character]
vimcmd_symbol = "[](bold surface1)"
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[directory]
truncate_to_repo = false
truncation_length = 2
fish_style_pwd_dir_length = 1
style = "overlay2"
repo_root_style = "bold blue"
before_repo_root_style = "surface1"

[package]
format = "is [$symbol$version]($style) "
symbol = " "
style = "peach dimmed"

[git_branch]
style = "dimmed lavender"

[git_status]
format="[$all_status$ahead_behind]($style)"
ahead="[ $ahead_count](green) "
behind="[ $behind_count](red) "
diverged="[ $ahead_count/$behind_count](yellow) "
up_to_date=""
untracked="[ $count](subtext0) "
stashed=""
modified="[ $count](flamingo) "
staged="[ $count](green) "
renamed="[ $count](yellow) "
deleted="[ $count](red) "


[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
