-- local packer = require 'packer'
-- local use = packer.use

-- use {
--   'luukvbaal/statuscol.nvim',
--   disable = true,
--   requires = { 'lewis6991/gitsigns.nvim' },
--   config = function()
--     require('statuscol').setup {
--       separator = ' ', -- separator between line number and buffer text ("│" or extra " " padding)
--
--       -- Builtin line number string options for ScLn() segment
--       thousands = false, -- or line number thousands separator string ("." / ",")
--       relculright = false, -- whether to right-align the cursor line number with 'relativenumber' set
--
--       -- Custom line number string options for ScLn() segment
--       lnumfunc = nil, -- custom function called by ScLn(), should return a string
--       reeval = false, -- whether or not the string returned by lnumfunc should be reevaluated
--
--       -- Builtin 'statuscolumn' options
--       setopt = true, -- whether to set the 'statuscolumn', providing builtin click actions
--       order = 'sFsNs', -- order of the fold, sign, line number and separator segments
--     }
--   end,
-- }
