#!/usr/bin/env fish
# fish completion support for wmill vv1.103.0

function __fish_wmill_using_command
  set -l cmds __wmill __wmill_app __wmill_app_push __wmill_flow __wmill_flow_push __wmill_flow_run __wmill_script __wmill_script_push __wmill_script_show __wmill_script_run __wmill_workspace __wmill_workspace_switch __wmill_workspace_add __wmill_workspace_remove __wmill_workspace_whoami __wmill_resource __wmill_resource_push __wmill_user __wmill_user_add __wmill_user_remove __wmill_user_create_token __wmill_variable __wmill_variable_push __wmill_hub __wmill_hub_pull __wmill_folder __wmill_folder_push __wmill_sync __wmill_sync_pull __wmill_sync_push __wmill_version __wmill_upgrade __wmill_completions __wmill_completions_bash __wmill_completions_fish __wmill_completions_zsh
  set -l words (commandline -opc)
  set -l cmd "_"
  for word in $words
    switch $word
      case '-*'
        continue
      case '*'
        set word (string replace -r -a '\W' '_' $word)
        set -l cmd_tmp $cmd"_$word"
        if contains $cmd_tmp $cmds
          set cmd $cmd_tmp
        end
    end
  end
  if test "$cmd" = "$argv[1]"
    return 0
  end
  return 1
end

complete -c wmill -n '__fish_wmill_using_command __wmill' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -s V -l version -x -k -f -d 'Show the version number for this program.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -l workspace -k -f -r -a '(wmill completions complete string )' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill' -l token -k -f -r -a '(wmill completions complete string )' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a app -d 'app related commands'
complete -c wmill -n '__fish_wmill_using_command __wmill_app' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_app' -l workspace -k -f -r -a '(wmill completions complete string app)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_app' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_app' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_app' -l token -k -f -r -a '(wmill completions complete string app)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_app' -k -f -a push -d 'push a local app'
complete -c wmill -n '__fish_wmill_using_command __wmill_app_push' -k -f -a '(__fish_complete_path)'
complete -c wmill -n '__fish_wmill_using_command __wmill_app_push' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_app_push' -l workspace -k -f -r -a '(wmill completions complete string app push)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_app_push' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_app_push' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_app_push' -l token -k -f -r -a '(wmill completions complete string app push)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a flow -d 'flow related commands'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow' -l workspace -k -f -r -a '(wmill completions complete string flow)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow' -l token -k -f -r -a '(wmill completions complete string flow)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow' -l show-archived -k -f -d 'Enable archived scripts in output'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow' -k -f -a push -d 'push a local flow spec. This overrides any remote versions.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_push' -k -f -a '(wmill completions complete string flow push)'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_push' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_push' -l workspace -k -f -r -a '(wmill completions complete string flow push)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_push' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_push' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_push' -l token -k -f -r -a '(wmill completions complete string flow push)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow' -k -f -a run -d 'run a flow by path.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_run' -k -f -a '(wmill completions complete string flow run)'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_run' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_run' -l workspace -k -f -r -a '(wmill completions complete string flow run)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_run' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_run' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_run' -l token -k -f -r -a '(wmill completions complete string flow run)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_run' -s d -l data -k -f -r -a '(wmill completions complete string flow run)' -d 'Inputs specified as a JSON string or a file using @<filename> or stdin using @-.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_run' -s s -l silent -k -f -d 'Do not ouput anything other then the final output. Useful for scripting.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a script -d 'script related commands'
complete -c wmill -n '__fish_wmill_using_command __wmill_script' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script' -l workspace -k -f -r -a '(wmill completions complete string script)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_script' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_script' -l token -k -f -r -a '(wmill completions complete string script)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script' -l show-archived -k -f -d 'Enable archived scripts in output'
complete -c wmill -n '__fish_wmill_using_command __wmill_script' -k -f -a push -d 'push a local script spec. This overrides any remote versions. Use the script file (.ts, .js, .py, .sh)'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_push' -k -f -a '(__fish_complete_path)'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_push' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_push' -l workspace -k -f -r -a '(wmill completions complete string script push)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_push' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_push' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_push' -l token -k -f -r -a '(wmill completions complete string script push)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script' -k -f -a show -d 'show a scripts content'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_show' -k -f -a '(__fish_complete_path)'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_show' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_show' -l workspace -k -f -r -a '(wmill completions complete string script show)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_show' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_show' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_show' -l token -k -f -r -a '(wmill completions complete string script show)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script' -k -f -a run -d 'run a script by path'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_run' -k -f -a '(__fish_complete_path)'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_run' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_run' -l workspace -k -f -r -a '(wmill completions complete string script run)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_run' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_run' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_run' -l token -k -f -r -a '(wmill completions complete string script run)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_run' -s d -l data -k -f -r -a '(__fish_complete_path)' -d 'Inputs specified as a JSON string or a file using @<filename> or stdin using @-.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_run' -s s -l silent -k -f -d 'Do not ouput anything other then the final output. Useful for scripting.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a workspace -d 'workspace related commands'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace' -l workspace -k -f -r -a '(wmill completions complete string workspace)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace' -l token -k -f -r -a '(wmill completions complete string workspace)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace' -k -f -a switch -d 'Switch to another workspace'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_switch' -k -f -a '(wmill completions complete workspace workspace switch)'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_switch' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_switch' -l workspace -k -f -r -a '(wmill completions complete string workspace switch)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_switch' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_switch' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_switch' -l token -k -f -r -a '(wmill completions complete string workspace switch)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace' -k -f -a add -d 'Add a workspace'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_add' -k -f -a '(wmill completions complete string workspace add)'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_add' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_add' -l workspace -k -f -r -a '(wmill completions complete string workspace add)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_add' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_add' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_add' -l token -k -f -r -a '(wmill completions complete string workspace add)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_add' -s c -l create -k -f -d 'Create the workspace if it does not exist'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_add' -l create-workspace-name -k -f -r -a '(wmill completions complete string workspace add)' -d 'Specify the workspace name. Ignored if --create is not specified or the workspace already exists. Will default to the workspace id.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_add' -l create-username -k -f -r -a '(wmill completions complete string workspace add)' -d 'Specify your own username in the newly created workspace. Ignored if --create is not specified or the workspace already exists.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace' -k -f -a remove -d 'Remove a workspace'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_remove' -k -f -a '(wmill completions complete string workspace remove)'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_remove' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_remove' -l workspace -k -f -r -a '(wmill completions complete string workspace remove)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_remove' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_remove' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_remove' -l token -k -f -r -a '(wmill completions complete string workspace remove)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace' -k -f -a whoami -d 'Show the currently active user'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_whoami' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_whoami' -l workspace -k -f -r -a '(wmill completions complete string workspace whoami)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_whoami' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_whoami' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_whoami' -l token -k -f -r -a '(wmill completions complete string workspace whoami)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a resource -d 'resource related commands'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource' -l workspace -k -f -r -a '(wmill completions complete string resource)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource' -l token -k -f -r -a '(wmill completions complete string resource)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource' -k -f -a push -d 'push a local resource spec. This overrides any remote versions.'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource_push' -k -f -a '(wmill completions complete string resource push)'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource_push' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource_push' -l workspace -k -f -r -a '(wmill completions complete string resource push)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource_push' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource_push' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource_push' -l token -k -f -r -a '(wmill completions complete string resource push)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a user -d 'user related commands'
complete -c wmill -n '__fish_wmill_using_command __wmill_user' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user' -l workspace -k -f -r -a '(wmill completions complete string user)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_user' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_user' -l token -k -f -r -a '(wmill completions complete string user)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user' -k -f -a add -d 'Create a user'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_add' -k -f -a '(wmill completions complete string user add)'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_add' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_add' -l workspace -k -f -r -a '(wmill completions complete string user add)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_add' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_add' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_add' -l token -k -f -r -a '(wmill completions complete string user add)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_add' -l superadmin -k -f -d 'Specify to make the new user superadmin.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_add' -l company -k -f -r -a '(wmill completions complete string user add)' -d 'Specify to set the company of the new user.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_add' -l name -k -f -r -a '(wmill completions complete string user add)' -d 'Specify to set the name of the new user.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user' -k -f -a remove -d 'Delete a user'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_remove' -k -f -a '(wmill completions complete string user remove)'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_remove' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_remove' -l workspace -k -f -r -a '(wmill completions complete string user remove)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_remove' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_remove' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_remove' -l token -k -f -r -a '(wmill completions complete string user remove)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user' -k -f -a create-token
complete -c wmill -n '__fish_wmill_using_command __wmill_user_create_token' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_create_token' -l workspace -k -f -r -a '(wmill completions complete string user create-token)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_create_token' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_create_token' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_create_token' -l token -k -f -r -a '(wmill completions complete string user create-token)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_create_token' -l email -k -f -r -a '(wmill completions complete string user create-token)' -d 'Specify credentials to use for authentication. This will not be stored. It will only be used to exchange for a token with the API server, which will not be stored either.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_create_token' -l password -k -f -r -a '(wmill completions complete string user create-token)' -d 'Specify credentials to use for authentication. This will not be stored. It will only be used to exchange for a token with the API server, which will not be stored either.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a variable -d 'variable related commands'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable' -l workspace -k -f -r -a '(wmill completions complete string variable)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable' -l token -k -f -r -a '(wmill completions complete string variable)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable' -k -f -a push -d 'Push a local variable spec. This overrides any remote versions.'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_push' -k -f -a '(wmill completions complete string variable push)'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_push' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_push' -l workspace -k -f -r -a '(wmill completions complete string variable push)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_push' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_push' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_push' -l token -k -f -r -a '(wmill completions complete string variable push)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_push' -l plain-secrets -k -f -d 'Push secrets as plain text'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a hub -d 'Hub related commands. EXPERIMENTAL. INTERNAL USE ONLY.'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub' -l workspace -k -f -r -a '(wmill completions complete string hub)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub' -l token -k -f -r -a '(wmill completions complete string hub)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub' -k -f -a pull -d 'pull any supported defintions. EXPERIMENTAL.'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub_pull' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub_pull' -l workspace -k -f -r -a '(wmill completions complete string hub pull)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub_pull' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub_pull' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub_pull' -l token -k -f -r -a '(wmill completions complete string hub pull)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a folder -d 'folder related commands'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder' -l workspace -k -f -r -a '(wmill completions complete string folder)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder' -l token -k -f -r -a '(wmill completions complete string folder)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder' -k -f -a push -d 'push a local folder spec. This overrides any remote versions.'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder_push' -k -f -a '(wmill completions complete string folder push)'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder_push' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder_push' -l workspace -k -f -r -a '(wmill completions complete string folder push)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder_push' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder_push' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder_push' -l token -k -f -r -a '(wmill completions complete string folder push)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a sync
complete -c wmill -n '__fish_wmill_using_command __wmill_sync' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync' -l workspace -k -f -r -a '(wmill completions complete string sync)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync' -l token -k -f -r -a '(wmill completions complete string sync)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync' -k -f -a pull -d 'Pull any remote changes and apply them locally. Use --raw for usage without local state tracking.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l workspace -k -f -r -a '(wmill completions complete string sync pull)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l token -k -f -r -a '(wmill completions complete string sync pull)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l fail-conflicts -k -f -d 'Error on conflicts (both remote and local have changes on the same item)'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l yes -k -f -d 'Pull without needing confirmation'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l raw -k -f -d 'Pull without using state, just overwrite.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l plain-secrets -k -f -d 'Pull secrets as plain text'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l json -k -f -d 'Use JSON instead of YAML'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync' -k -f -a push -d 'Push any local changes and apply them remotely. Use --raw for usage without local state tracking.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l workspace -k -f -r -a '(wmill completions complete string sync push)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l token -k -f -r -a '(wmill completions complete string sync push)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l fail-conflicts -k -f -d 'Error on conflicts (both remote and local have changes on the same item)'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l skip-pull -k -f -d 'Push without pulling first (you have pulled prior)'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l yes -k -f -d 'Push without needing confirmation'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l raw -k -f -d 'Push without using state, just overwrite.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l plain-secrets -k -f -d 'Push secrets as plain text'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l json -k -f -d 'Use JSON instead of YAML'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a version -d 'Show version information'
complete -c wmill -n '__fish_wmill_using_command __wmill_version' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_version' -l workspace -k -f -r -a '(wmill completions complete string version)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_version' -l debug -k -f -d 'Show debug logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_version' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_version' -l token -k -f -r -a '(wmill completions complete string version)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a upgrade -d 'Upgrade wmill executable to latest or given version.'
complete -c wmill -n '__fish_wmill_using_command __wmill_upgrade' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_upgrade' -s l -l list-versions -k -f -d 'Show available versions.'
complete -c wmill -n '__fish_wmill_using_command __wmill_upgrade' -l version -k -f -r -a '(wmill completions complete version upgrade)' -d 'The version to upgrade to.'
complete -c wmill -n '__fish_wmill_using_command __wmill_upgrade' -s f -l force -k -f -d 'Replace current installation even if not out-of-date.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a completions -d 'Generate shell completions.'
complete -c wmill -n '__fish_wmill_using_command __wmill_completions' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_completions' -k -f -a bash -d 'Generate shell completions for bash.'
complete -c wmill -n '__fish_wmill_using_command __wmill_completions_bash' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_completions' -k -f -a fish -d 'Generate shell completions for fish.'
complete -c wmill -n '__fish_wmill_using_command __wmill_completions_fish' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_completions' -k -f -a zsh -d 'Generate shell completions for zsh.'
complete -c wmill -n '__fish_wmill_using_command __wmill_completions_zsh' -s h -l help -x -k -f -d 'Show this help.'
