#!/usr/bin/env zsh

#################
# System Config #
#################

# Recognise and configure the second screen
setsid $HOME/.screenlayout/layout.sh &> /dev/null
#
# ################
# # Applications #
# ################
#
# # If the scratchpad isn't running, let's relaunch it.
if [[ -z $(xdotool search --class scratchpad) ]]; then 
	# Launch a scratchpad console; it will be floated and hidden by the window manager
	setsid $TERM --class scratchpad &> /dev/null
fi

# # Set the background image
# # No harm in re-running this.
source $HOME/.fehbg
